[25/Feb/2019 14:31:07] INFO [django.server] [log_message:154] "GET /accounts/login/ HTTP/1.1" 200 1566
[25/Feb/2019 14:31:08] INFO [django.server] [log_message:154] "POST /accounts/login/ HTTP/1.1" 302 0
[25/Feb/2019 14:31:08] ERROR [django.request] [log_response:228] Internal Server Error: /users/profile/
Traceback (most recent call last):
  File "C:\Python36\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Python36\lib\site-packages\django\utils\deprecation.py", line 93, in __call__
    response = self.process_response(request, response)
  File "C:\Python36\lib\site-packages\django\middleware\clickjacking.py", line 26, in process_response
    if response.get('X-Frame-Options') is not None:
  File "C:\Python36\lib\site-packages\django\utils\functional.py", line 214, in inner
    return func(self._wrapped, *args)
AttributeError: 'CustomUser' object has no attribute 'get'
[25/Feb/2019 14:31:08] ERROR [django.server] [log_message:154] "GET /users/profile/ HTTP/1.1" 500 69986
