[25/Feb/2019 13:46:54] INFO [ai.classifier] [__init__:15] Classifier created: mock
[25/Feb/2019 13:47:00] INFO [django.server] [log_message:154] "GET /accounts/login/ HTTP/1.1" 200 1566
[25/Feb/2019 13:47:00] INFO [django.server] [log_message:154] "GET /accounts/login/ HTTP/1.1" 200 1566
[25/Feb/2019 13:47:00] INFO [django.server] [log_message:154] "POST /accounts/login/ HTTP/1.1" 302 0
[25/Feb/2019 13:47:00] INFO [django.server] [log_message:154] "POST /accounts/login/ HTTP/1.1" 302 0
[25/Feb/2019 13:47:01] ERROR [django.request] [log_response:228] Internal Server Error: /users/profile/
Traceback (most recent call last):
  File "C:\Python36\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Python36\lib\site-packages\django\utils\deprecation.py", line 93, in __call__
    response = self.process_response(request, response)
  File "C:\Python36\lib\site-packages\django\middleware\clickjacking.py", line 26, in process_response
    if response.get('X-Frame-Options') is not None:
  File "C:\Python36\lib\site-packages\django\utils\functional.py", line 214, in inner
    return func(self._wrapped, *args)
AttributeError: 'CustomUser' object has no attribute 'get'
[25/Feb/2019 13:47:01] ERROR [django.server] [log_message:154] "GET /users/profile/ HTTP/1.1" 500 69983
[25/Feb/2019 13:47:01] ERROR [django.server] [log_message:154] "GET /users/profile/ HTTP/1.1" 500 69983
[25/Feb/2019 13:47:01] INFO [core.views] [post:30] Some files are in the request, processing started..
[25/Feb/2019 13:47:06] INFO [ai.classification] [find_creator_and_verify_permissions:29] szabag@gmail.com requested a new classification
[25/Feb/2019 13:47:09] INFO [ai.classification] [save_picture_and_create_imagedata:34] Processing image file data 430.jpg 
[25/Feb/2019 13:47:15] INFO [ai.classification] [save_picture_and_create_imagedata:43] New imagefile saved with id 7 
[25/Feb/2019 13:47:24] INFO [ai.classification] [save_picture_and_create_imagedata:54] Image saved into C:\CR\IMAGES\szabag\ 
[25/Feb/2019 13:47:26] INFO [ai.classification] [classify:60] Classification started for image 430 by user szabag
